version: '3.4'

services:
  divartelegrambot:
    image: idebman/divartelegrambot
    build: .
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./tokens.json
        target: /app/tokens.json
